source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "9.0"
inhibit_all_warnings!

# 如果有库因为忽略警告而编译失败，单独给他设置不忽略警告
# pod 'ReactiveCocoa', '~> 2.1.8', :inhibit_warnings => true

target 'WVRMediator' do

    pod "CTMediator"
    pod "YYModel"

end
